# Generated by Django 5.1.3 on 2024-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(choices=[('velog', 'Velog'), ('tistory', 'Tistory'), ('naver', 'Naver')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('tags', models.TextField()),
                ('interest', models.CharField(max_length=50)),
                ('write_at', models.CharField(max_length=50)),
            ],
        ),
    ]
