# Generated by Django 5.1.3 on 2024-12-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_final_post_delete_scrapedpost_final_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.final')),
            ],
        ),
    ]
